pr:
  branches:
    include:
    - main

pool:
  name: 'pipeline-practice-self-hosted'

variables:
  sonarCloudEndpointName: 'SC'
  sonarCloudOrganization: 'robertdpowell'
  sonarCloudProjectKey: 'robertdpowell_pythonpipeline'
  sonarCloudProjectName: 'PythonPipeline'
  dockerImageName: 'myapp:pr-check'

stages:
- stage: SonarCloudScan_TrivyScan
  displayName: 'SonarCloud-Scan & Trivy-Scan'
  jobs:
    - job: SonarCloudScan
      displayName: 'SonarCloud Scan'
      steps:
      - script: |
          # Determine JAVA_HOME dynamically and export it
          JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
          echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME"
          echo "JAVA_HOME set to $JAVA_HOME"
        displayName: 'Set JAVA_HOME'

      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: '$(sonarCloudEndpointName)'
          organization: '$(sonarCloudOrganization)'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: '$(sonarCloudProjectKey)'
          cliSources: '.'

      - task: SonarCloudAnalyze@1
        inputs:
          SonarCloud: '$(sonarCloudEndpointName)'

      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'
