name: Build, Tag and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version tag
        id: version
        run: echo "VERSION_TAG=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Used by SonarCloud to create checks on the GitHub pull request
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your SonarCloud token
        with:
          args: >
            -Dsonar.projectKey=my_project_key
            -Dsonar.organization=my_organization_key
            -Dsonar.sources=.
            

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build . -t acrpipelinepractice.azurecr.io/myapp:${{ env.VERSION_TAG }}

      - name: Scan the Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'acrpipelinepractice.azurecr.io/myapp:${{ env.VERSION_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: Push Docker image to ACR
        run: |
          az acr login --name acrpipelinepractice
          docker push acrpipelinepractice.azurecr.io/myapp:${{ env.VERSION_TAG }}

      - name: Create and push git tag
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action"
          git tag ${{ env.VERSION_TAG }}
          git push origin ${{ env.VERSION_TAG }}

