name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 17
        branch: main
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git


    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image to ACR
      run: |
        az acr login --name acrpipelinepractice
        docker build . -t acrpipelinepractice.azurecr.io/myapp:${{ github.sha }}
        docker push acrpipelinepractice.azurecr.io/myapp:${{ github.sha }}
