name: Build, Tag, and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate version tag
        id: version
        run: echo "VERSION_TAG=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . -t myapp:${{ env.VERSION_TAG }}

      - name: Log in to Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tag and Push to Docker Registry
        run: |
          docker tag myapp:${{ env.VERSION_TAG }} ${{ secrets.DOCKER_USERNAME }}/myapp:${{ env.VERSION_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ env.VERSION_TAG }}

      - name: Create and push git tag
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action"
          git tag ${{ env.VERSION_TAG }}
          git push origin ${{ env.VERSION_TAG }}
