name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Used by SonarCloud to create checks on the GitHub pull request
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your SonarCloud token
        with:
          args: >
            -Dsonar.projectKey=robertdpowell_pythonpipeline
            -Dsonar.organization=robertdpowell
            -Dsonar.sources=.
            -Dsonar.qualitygate.wait=true

  image-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: |
          docker build . -t myapp:pr-check

      - name: Scan the Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:pr-check'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL'

  codeql-analysis:
    name: Analyze
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

